stages:
  make_observed:
    cmd: >-
      poetry run python -m src.data.make_observed
      data/interim/observed.pickle
    deps:
    - src/data/make_observed.py
    outs:
    - data/interim/observed.pickle
  sampling:
    cmd: >-
      poetry run python -m src.models.sampling
      data/interim/observed.pickle
      models/model_and_trace.pickle
      --random_seed=1000
      --n_sampling=4000
      --n_tune=2000
      --n_chains=4
    deps:
    - src/models/sampling.py
    - data/interim/observed.pickle
    outs:
    - models/model_and_trace.pickle
  visualization:
    cmd: >-
      poetry run python -m src.visualization.visualize
      models/model_and_trace.pickle
      data/interim/observed.pickle
      data/processed/result/
    deps:
    - src/visualization/visualize.py
    - src/utils.py
    - models/model_and_trace.pickle
    - data/interim/observed.pickle
    outs:
    - data/processed/result/
  make_observed_explore:
    foreach: ${explore}
    do:
      cmd: >-
        poetry run python -m src.data.make_observed
        data/interim/observed_${key}.pickle
        --random_state=${item.random_seed}
      deps:
      - src/data/make_observed.py
      outs:
      - data/interim/observed_${key}.pickle
  sampling_explore:
    foreach: ${explore}
    do:
      cmd: >-
        poetry run python -m src.models.sampling
        data/interim/observed_${key}.pickle
        models/explore/model_and_trace_${key}.pickle
        --random_seed=${item.random_seed}
        --n_sampling=4000
        --n_tune=2000
        --n_chains=4
      deps:
      - src/models/sampling.py
      - data/interim/observed_${key}.pickle
      outs:
      - models/explore/model_and_trace_${key}.pickle
  visualization_explore:
    foreach: ${explore}
    do:
      cmd: >-
        poetry run python -m src.visualization.visualize
        models/explore/model_and_trace_${key}.pickle
        data/interim/observed_${key}.pickle
        data/processed/explore/${key}/
        --figure_dir=reports/figures/explore/${key}/
      deps:
      - src/visualization/visualize.py
      - src/utils.py
      - models/explore/model_and_trace_${key}.pickle
      - data/interim/observed_${key}.pickle
      outs:
      - data/processed/explore/${key}/
