stages:
  make_dataset:
    cmd: >-
      poetry run python -m src.data.make_dataset
      data/interim/dataset.pickle
    deps:
    - src/data/make_dataset.py
    outs:
    - data/interim/dataset.pickle
  sampling:
    cmd: >-
      poetry run python -m src.models.sampling
      data/interim/dataset.pickle
      data/interim/model_and_trace.pickle
    deps:
    - src/models/sampling.py
    - data/interim/dataset.pickle
    outs:
    - data/interim/model_and_trace.pickle
  visualization:
    cmd: >-
      poetry run python -m src.visualization.visualize
      data/interim/model_and_trace.pickle
      data/interim/dataset.pickle
      data/processed/result/
    deps:
    - src/visualization/visualize.py
    - data/interim/model_and_trace.pickle
    - data/interim/dataset.pickle
    outs:
    - data/processed/result/
